name: Approve PR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number'
        required: true

jobs:
  approve_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Get PR info
        id: pr_info
        run: gh pr view ${{ inputs.pr_number }} --json author -q '.author.login'

      - name: Validate Actor
        run: |
          if [ "${{ steps.pr_info.outputs }}" == "${{ github.actor }}" ]; then
            echo "::error:: You can't approve your own PR"
            exit 1
          fi

      - name: Merge pull request
        run: |
          Write-Host "Waiting for checks to start..."
          Start-Sleep -Seconds 180
          Write-Host "Checking if checks have started..."
          gh pr checks --watch --fail-fast
          gh pr merge --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.DEVOLUTIONSBOT_WRITE_TOKEN }}
